### PR TITLE
Add GDX Snowplow tracker

### PR DESCRIPTION
**Pull request by michaelpnelson**
link to demo deployment of your smk based app is 
 https://smk-mrdt-rt-b16795-dev.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @dgboss, @NicoledeGreef

### CODE REVIEW

**Comment by dgboss** [comment]
The Vanity URL for the dev deploy is https://smk-mrdt-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @dgboss, @NicoledeGreef

**Review by dgboss — APPROVED** [review]

**Comment by dgboss** [comment]
My only suggestions would be to rebase anytime you are creating a PR for a client's app. For this PR, you are using a stale smk-config.json, so if the client happens to look at the dev/test app right now, they won't see the changes I made recently and may wonder why the changes were reverted.

**Comment by michaelpnelson** [comment]
Sorry Darren! I didn't realize you had further changes being tested. 

I'll close this PR and create a new one from a branch that has the analytics change rebased on the main branch.

**Comment by dgboss** [comment]
I don't have further changes being tested for the dev branch, my PR has already been merged and my changes were live in the dev environment.

Since your feature branch is stale and it's code has been deployed to the development environment, the app that is displaying in dev is also stale.

No need to close this PR, you should just be able to rebase and force push top your feature branch.

**Pull request closed without merging**
